Merge bitcoin/bitcoin#26294: build: move util/url to common/url
3a0b352c63db543833e0f919a004cf2c5093fe9c refactor: move url.h/cpp from lib util to lib common (fanquake)
058eb69ce47c17205a41fc667ce66429f09a332a build: add missing event cflags to libbitcoin_util (fanquake)

Pull request description:

  Move `util/url` to `common/url`.

  Also add missing `event_*` flags to `libbitcoin_util`. #26293 + the commit dropping boost cppflags from `libbitcoin_util` shows this issue. i.e:
  ```bash
    CXX      util/libbitcoin_util_a-url.o
  util/url.cpp:7:10: fatal error: 'event2/http.h' file not found
  #include <event2/http.h>
           ^~~~~~~~~~~~~~~
  1 error generated.
  ```

ACKs for top commit:
  hebasto:
    ACK 3a0b352c63db543833e0f919a004cf2c5093fe9c
  ryanofsky:
    Code review ACK 3a0b352c63db543833e0f919a004cf2c5093fe9c

Tree-SHA512: 600a76fd334267a02d332df9b67891a38d3fd7f5baf8a82b2447879b3bc65eab2552d2c081c0a5f1ec927bf80df7fc1f0cbbdda4cb76994b46dadf260b8e1cb3